title: "ShikhaShikz"
email: shikhapakhide@gmail.com
timezone: UTC
baseurl: "/shikhashikz"
permalink: "/:title/"
#logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: shikhashikz
paginate: 30
disqus: 'shikhashikz-com'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-84084860-1

# Authors
authors:
  shikhashikz:
    name: shikhashikz
    display_name: shikhashikz
    avatar: 'assets/images/sal.png'
    email: shikhapakhide@gmail.com
    web: https://shikhashikz.com
    twitter: https://twitter.com/shikhashikz
    description: "Creates the Zing factor in Marketing | Books are my Best Friend , Tea is my favorite beverage & Travelling to places is my hobby | A story teller."

# Social
social:
  instagram: https://www.instagram.com/shikhashikz/
  facebook: https://www.facebook.com/shikhashikz1
  twitter: https://twitter.com/shikhashikz

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives