permalink: /:categories/:title.html
url: "http://shikhashikz.com"
full_name: "shikhashikz.com"
first_name: "shikhashikz"
last_name: ""
blog_title: "shikhashikz "
author_img_name_path: "/images/users/shikhashikz.jpg"
disqus_shortname: "shikhasite"
copyright_year: "2016"
google_analytics_code: "UA-84084860-1"
aboutme: "Creates the Zing factor in Marketing | Books are my Best Friend , Tea is my favorite beverage & Travelling to places is my hobby | A story teller"
twitter: "shikhashikz"
github: "shikhashikz"
facebook: "shikhashikz"
linkined_url: "https://www.linkedin.com/in/shikha"

theme: jekyll-theme-tactile